<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Apostilas"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soapenc="http://schemas.xmlsoap.com/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://localhost/502/aula03/SOAP/server.php">

    <wsdl:message name="getUsersOut">
        <wsdl:part name="getUsers" type="xsd:json"></wsdl:part>
    </wsdl:message>

    <wsdl:portType name="UsersPortType">
        <wsdl:operation name="list">
            <wsdl:output message="tns:getUsersOut"></wsdl:output>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="UsersBinding" type="tns:UsersPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="list">
            <wsdl:output>
                <soap:body use="encoded" namespace="urn:Users"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="Users">
        <wsdl:port name="UsersPort" binding="tns:UsersBinding">
            <soap:address location="http://localhost/502/aula03/SOAP/server.php"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>